//await is used as promise to resolve error/ question in JS
const answers = await  function(){try{
    
} catch (error) {
    
}(err:any)  =>{
    console.log(err);
    return "default answers";
}; 
} 

